branch-defaults:
  master:
    environment: null
environment-defaults:
  Jokerrank-env:
    branch: null
    repository: null
global:
  application_name: jokerrank
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Node.js running on
    64bit Amazon Linux/4.7.1
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
